### PR TITLE
User Story 6: Submit An Application

### LINKED ISSUE #9: 6. Submit an Application
As a visitor
When I visit an application's show page
And I have added one or more pets to the application
Then I see a section to submit my application
And in that section I see an input to enter why I would make a good owner for these pet(s)
When I fill in that input
And I click a button to submit this application
Then I am taken back to the application's show page
And I see an indicator that the application is "Pending"
And I see all the pets that I want to adopt
And I do not see a section to add more pets to this application

### LINKED ISSUE #10: 7. No Pets on an Application
As a visitor
When I visit an application's show page
And I have not added any pets to the application
Then I do not see a section to submit my application

### PR DESCRIPTION
**Pull request by ethanrossblack**
This user story completes User Story 6: Submitting an Application AND User Story 7: No Pets on an Application.

I ended up changing the schema for the Application model, adding a `description_owner` column for the Applications table. See the migrations file. Along with this, I think it might be worthwhile to change the name of the previous `description` attribute to something like `description_home`, based off of their descriptions in the user story. My reasoning is that 
* User Story 2 asks for a form field for a `Description of why I would make a good home.`
* User Story 6 asks for `an input to enter why I would make a good owner for these pet(s).`
One asks why you would make a good **_home_** in general for a pet, and the other asks why you would be a good **_owner_** for **_specific_** pets.

In addition to the completion of User Stories 6+7, I also added some formatting
* I added a link and some nav bars to make pages easier to navigate (see pic)
Screenshot 2023-07-16 at 2 23 19 AM
* I also added some formatting for how pets are listed on the Show page. I put the pets into an unordered list (`<ul>`). See the code for more details
Screenshot 2023-07-16 at 2 24 16 AM
* I added a line to our `spec_helper` file to make the results look nicer in the terminal and like documentation
Screenshot 2023-07-16 at 2 26 39 AM

---
Things I should add to this PR
* Functionality where the `description_owner` appears on the show page after submission (and tests)

---
Closes #9
Closes #10

### CODE REVIEW

**Comment by ethanrossblack** [comment]
This PR will have merge conflicts with the other two PRs in the pipeline, so we should resolve those issues first before merging this one.

**Comment by ethanrossblack** [comment]
I added a test so this PR now completes user stories 6+7.

**Review by pcbennett108 — APPROVED** [review]
Live interaction follows user story.
Tests look complete.
The basic formatting changes made a striking improvement to readability and page presence.

**Review by garussell — APPROVED** [review]
This looks great!

**Pull request merged**
